project:
  type: website
  render:
    - "slides/*.qmd"
    - "notes/*.qmd"

website:
  title: "CS 5220 Slides and Notes"
  site-url: https://www.cs.cornell.edu/courses/cs5220/2024fa

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
